### ISSUE TITLE
Cannot center .odometer container element without using !important or padding

### ISSUE THREAD

**Issue by ZachMoreno** [HubSpot/odometer#26]
Please correct me if I'm mistaken, but to effectively center the .odometer container element you have to use <code>!important</code> to override a few CSS rules. The default styles within odometer-theme-default.css (lines 1-9) are

``` css
.odometer.odometer-auto-theme, .odometer.odometer-theme-default {
  display: -moz-inline-box;
  -moz-box-orient: vertical;
  display: block;
  vertical-align: middle;
  *vertical-align: auto;
  position: relative;
  position: relative;
}
```

to center the .odometer container the following overrides are necessary & are not applied without <code>!important</code>

``` css
.odometer {
    text-align: center !important;
    display: block !important;
    font-family: 'roboto' !important;
}
```

or

``` css
.odometer {
    padding: 60px 129px;
}
```

works without <code>!important</code> but is much more difficult to center considered in the context of media queries. Padding is how the GitHub Stars odometer is working on http://github.hubspot.com/odometer/.

The default theme also enforces Helvetica Neue as the font family & this too requires !important to override. Why not just use 

``` css
.odometer.odometer-auto-theme, .odometer.odometer-theme-default {
    font-family: inherit;
}
```

?

The cascade of my stylesheets is in the correct order with my custom styles referenced below odometer-theme-default.css & therefore is not the cause of this issue.
